-- Table Creation

CREATE TABLE Provinces (
  Code VARCHAR(2) PRIMARY KEY,
  Description VARCHAR(50)
)
CREATE TABLE Municipalities (
  ProvinceCode VARCHAR(2) FOREIGN KEY(ProvinceCode) REFERENCES Provinces(Code),
  Code VARCHAR(5),
  Description VARCHAR(50),
)

-- Table Inserts

INSERT INTO Provinces(Code, Description) VALUES('AZ', 'Azua')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AZ', 'AZ.AC', 'Azua')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AZ', 'AZ.ES', 'Estebanía')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AZ', 'AZ.GU', 'Guayabal')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AZ', 'AZ.LC', 'Las Charcas')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AZ', 'AZ.YV', 'Las Yayas de Viajama')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AZ', 'AZ.PL', 'Padre las Casas')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AZ', 'AZ.PR', 'Peralta')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AZ', 'AZ.PV', 'Pueblo Viejo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AZ', 'AZ.SY', 'Sabana Yegua')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AZ', 'AZ.VT', 'Tábara Arriba')

INSERT INTO Provinces(Code, Description) VALUES('BR', 'Baoruco')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BR', 'BR.GA', 'Galván')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BR', 'BR.LR', 'Los Ríos')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BR', 'BR.NE', 'Neiba')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BR', 'BR.TM', 'Tamayo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BR', 'BR.VJ', 'Villa Jaragua')

INSERT INTO Provinces(Code, Description) VALUES('BH', 'Barahona')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BH', 'BH.SC', 'Barahona')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BH', 'BH.CA', 'Cabral')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BH', 'BH.EP', 'El Peñón')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BH', 'BH.EN', 'Enriquillo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BH', 'BH.FU', 'Fundación')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BH', 'BH.JQ', 'Jaquimeyes')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BH', 'BH.LC', 'La Ciénaga')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BH', 'BH.LS', 'Las Salinas')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BH', 'BH.PA', 'Paraíso')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BH', 'BH.PO', 'Polo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('BH', 'BH.VN', 'Vicente Noble')

INSERT INTO Provinces(Code, Description) VALUES('DA', 'Dajabón')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DA', 'DA.DA', 'Dajabón')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DA', 'DA.EP', 'El Pino')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DA', 'DA.LC', 'Loma de Cabrera')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DA', 'DA.PA', 'Partido')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DA', 'DA.RE', 'Restauración')

INSERT INTO Provinces(Code, Description) VALUES('NC', 'Distrito Nacional')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('NC', 'NC.DN', 'Santo Domingo de Guzmán')

INSERT INTO Provinces(Code, Description) VALUES('DU', 'Duarte')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DU', 'DU.AR', 'Arenoso')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DU', 'DU.CA', 'Castillo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DU', 'DU.HO', 'Eugenio María de Hostos')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DU', 'DU.LG', 'Las Guáranas')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DU', 'DU.PI', 'Pimentel')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DU', 'DU.SF', 'San Francisco de Macorís')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('DU', 'DU.VR', 'Villa Riva')

INSERT INTO Provinces(Code, Description) VALUES('EP', 'Elías Piña')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('EP', 'EP.BA', 'Bánica')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('EP', 'EP.CO', 'Comendador')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('EP', 'EP.EL', 'El Llano')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('EP', 'EP.HV', 'Hondo Valle')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('EP', 'EP.JS', 'Juan Santiago')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('EP', 'EP.PS', 'Pedro Santana')

INSERT INTO Provinces(Code, Description) VALUES('SE', 'El Seibo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SE', 'SE.SC', 'El Seibo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SE', 'SE.MI', 'Miches')

INSERT INTO Provinces(Code, Description) VALUES('ES', 'Espaillat')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ES', 'ES.CG', 'Cayetano Germosén')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ES', 'ES.GH', 'Gaspar Hernández')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ES', 'ES.JN', 'Jamao al Norte')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ES', 'ES.MC', 'Moca')

INSERT INTO Provinces(Code, Description) VALUES('HM', 'Hato Mayor')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('HM', 'HM.EV', 'El Valle')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('HM', 'HM.HM', 'Hato Mayor')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('HM', 'HM.SM', 'Sabana de la Mar')

INSERT INTO Provinces(Code, Description) VALUES('SC', 'Hermanas Mirabal')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SC', 'SC.SA', 'Salcedo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SC', 'SC.TE', 'Tenares')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SC', 'SC.VT', 'Villa Tapia')

INSERT INTO Provinces(Code, Description) VALUES('IN', 'Independencia')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('IN', 'IN.CR', 'Cristóbal')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('IN', 'IN.DU', 'Duvergé')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('IN', 'IN.JI', 'Jimaní')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('IN', 'IN.LD', 'La Descubierta')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('IN', 'IN.ME', 'Mella')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('IN', 'IN.PR', 'Postrer Río')

INSERT INTO Provinces(Code, Description) VALUES('AL', 'La Altagracia')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AL', 'AL.HI', 'Higüey')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('AL', 'AL.SR', 'San Rafael del Yuma')

INSERT INTO Provinces(Code, Description) VALUES('RO', 'La Romana')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('RO', 'RO.GU', 'Guaymate')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('RO', 'RO.LR', 'La Romana')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('RO', 'RO.VH', 'Villa Hermosa')

INSERT INTO Provinces(Code, Description) VALUES('VE', 'La Vega')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('VE', 'VE.CO', 'Constanza')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('VE', 'VE.JB', 'Jarabacoa')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('VE', 'VE.JA', 'Jima Abajo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('VE', 'VE.CV', 'La Vega')

INSERT INTO Provinces(Code, Description) VALUES('MT', 'María Trinidad Sánchez')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MT', 'MT.CA', 'Cabrera')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MT', 'MT.EF', 'El Factor')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MT', 'MT.NA', 'Nagua')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MT', 'MT.RS', 'Río San Juan')

INSERT INTO Provinces(Code, Description) VALUES('MN', 'Monseñor Nouel')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MN', 'MN.BO', 'Bonao')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MN', 'MN.MA', 'Maimón')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MN', 'MN.PB', 'Piedra Blanca')

INSERT INTO Provinces(Code, Description) VALUES('MC', 'Monte Cristi')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MC', 'MC.CA', 'Castañuelas')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MC', 'MC.GU', 'Guayubín')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MC', 'MC.LM', 'Las Matas de Santa Cruz')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MC', 'MC.SF', 'Monte Cristi')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MC', 'MC.PS', 'Pepillo Salcedo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MC', 'MC.VV', 'Villa Vásquez')

INSERT INTO Provinces(Code, Description) VALUES('MP', 'Monte Plata')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MP', 'MP.BA', 'Bayaguana')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MP', 'MP.MT', 'Monte Plata')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MP', 'MP.ES', 'Peralvillo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MP', 'MP.SG', 'Sabana Grande de Boyá')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('MP', 'MP.YA', 'Yamasá')

INSERT INTO Provinces(Code, Description) VALUES('PN', 'Pedernales')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PN', 'PN.OV', 'Oviedo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PN', 'PN.PE', 'Pedernales')

INSERT INTO Provinces(Code, Description) VALUES('PV', 'Peravia')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PV', 'PV.BN', 'Baní')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PV', 'PV.NI', 'Nizao')

INSERT INTO Provinces(Code, Description) VALUES('PP', 'Puerto Plata')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PP', 'PP.AL', 'Altamira')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PP', 'PP.GU', 'Guananico')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PP', 'PP.IM', 'Imbert')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PP', 'PP.LH', 'Los Hidalgos')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PP', 'PP.LU', 'Luperón')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PP', 'PP.SF', 'Puerto Plata')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PP', 'PP.SO', 'Sosúa')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PP', 'PP.LI', 'Villa Isabela')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PP', 'PP.VM', 'Villa Montellano')

INSERT INTO Provinces(Code, Description) VALUES('SM', 'Samaná')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SM', 'SM.LT', 'Las Terrenas')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SM', 'SM.SB', 'Samaná')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SM', 'SM.SA', 'Sánchez')

INSERT INTO Provinces(Code, Description) VALUES('SZ', 'Sánchez Ramírez')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SZ', 'SZ.CV', 'Cevicos')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SZ', 'SZ.CO', 'Cotuí')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SZ', 'SZ.FA', 'Fantino')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SZ', 'SZ.LM', 'La Mata')

INSERT INTO Provinces(Code, Description) VALUES('CR', 'San Cristóbal')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('CR', 'CR.BH', 'Bajos de Haina')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('CR', 'CR.CG', 'Cambita Garabitos')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('CR', 'CR.LC', 'Los Cacaos')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('CR', 'CR.SP', 'Sabana Grande de Palenque')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('CR', 'CR.SC', 'San Cristóbal')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('CR', 'CR.NI', 'San Gregorio de Nigua')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('CR', 'CR.VA', 'Villa Altagracia')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('CR', 'CR.SG', 'Yaguate')

INSERT INTO Provinces(Code, Description) VALUES('JO', 'San José de Ocoa')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('JO', 'JO.RA', 'Rancho Arriba')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('JO', 'JO.SL', 'Sabana Larga')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('JO', 'JO.SJ', 'San José de Ocoa')

INSERT INTO Provinces(Code, Description) VALUES('JU', 'San Juan')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('JU', 'JU.BO', 'Bohechío')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('JU', 'JU.EC', 'El Cercado')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('JU', 'JU.JH', 'Juan de Herrera')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('JU', 'JU.LM', 'Las Matas de Farfán')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('JU', 'JU.SJ', 'San Juan')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('JU', 'JU.VA', 'Vallejuelo')

INSERT INTO Provinces(Code, Description) VALUES('PM', 'San Pedro de Macorís')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PM', 'PM.CO', 'Consuelo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PM', 'PM.GY', 'Guayacanes')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PM', 'PM.LL', 'Los Llanos')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PM', 'PM.QQ', 'Quisqueya')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PM', 'PM.RS', 'Ramón Santana')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('PM', 'PM.SP', 'San Pedro de Macorís')

INSERT INTO Provinces(Code, Description) VALUES('ST', 'Santiago')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ST', 'ST.VB', 'Bisonó')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ST', 'ST.JA', 'Jánico')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ST', 'ST.LM', 'Licey al Medio')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ST', 'ST.PU', 'Puñal')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ST', 'ST.SI', 'Sabana Iglesia')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ST', 'ST.SJ', 'San José de las Matas')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ST', 'ST.SG', 'Santiago')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ST', 'ST.TA', 'Tamboril')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('ST', 'ST.VG', 'Villa González')

INSERT INTO Provinces(Code, Description) VALUES('SR', 'Santiago Rodríguez')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SR', 'SR.MO', 'Monción')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SR', 'SR.SI', 'San Ignacio de Sabaneta')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SR', 'SR.LA', 'Villa los Almácigos')

INSERT INTO Provinces(Code, Description) VALUES('SD', 'Santo Domingo')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SD', 'SD.BC', 'Boca Chica')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SD', 'SD.LA', 'Los Alcarrizos')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SD', 'SD.PB', 'Pedro Brand')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SD', 'SD.GU', 'San Antonio de Guerra')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SD', 'SD.ES', 'Santo Domingo Este')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SD', 'SD.DN', 'Santo Domingo Norte')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('SD', 'SD.OE', 'Santo Domingo Oeste')

INSERT INTO Provinces(Code, Description) VALUES('VA', 'Valverde')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('VA', 'VA.ES', 'Esperanza')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('VA', 'VA.LS', 'Laguna Salada')
INSERT INTO Municipalities(ProvinceCode, Code, Description) VALUES('VA', 'VA.MA', 'Mao')